<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<AssemblyName>SampleXamlLibrary</AssemblyName>
		<RootNamespace>SampleXamlLibrary</RootNamespace>
		<AssemblyVersion>2.0.0.0</AssemblyVersion>
		<FileVersion>2.0.0.0</FileVersion>
		<Version>2.0.0.0</Version>
	</PropertyGroup>

</Project>
